---
title: "Práctica 2: Arquitectura y prototipo funcional del proyecto"
subtitle: "Link al repositorio: [https://github.com/azulnogueraa/Proyecto_AW](https://github.com/azulnogueraa/Proyecto_AW)"
author:
    - "Azul Noguera" 
    - "Patricio Guledjian"
    - "Rocio Gonzalez Cingolani"
    - "Vincent Jasou"
    - "Gabriel Zamy"
date: "`r Sys.Date()`"
lang: "es-ES"
output: 
    pdf_document
toc: true
bibliography: bibliography.bib
---
\newpage

\section*{Memoria de la estructura del proyecto}

## Introducción

Learnique se presenta como una innovadora plataforma de educación en línea diseñada para transformar el panorama actual del aprendizaje digital. Distinguiéndose por su enfoque en la personalización, Learnique no solo ofrece acceso a una amplia gama de recursos educativos, sino que también adapta la experiencia de aprendizaje a las necesidades individuales de cada usuario. A través de la implementación de tecnologías avanzadas, Learnique busca optimizar la retención de información y maximizar la satisfacción del estudiante, ofreciendo una solución integral que va más allá de la mera transmisión de conocimientos teóricos. Esta plataforma es el resultado de un meticuloso análisis de las limitaciones presentes en los modelos educativos en línea convencionales, marcando el comienzo de una era donde el aprendizaje digital es genuinamente inclusivo, accesible y efectivo para todos. 

### Tipos de Usuarios

Learnique atiende a una diversidad de usuarios, cada uno con distintas metas y necesidades educativas. A continuación, se describen los principales tipos de usuarios y las funcionalidades específicas diseñadas para cada grupo:

- Estudiantes:
Individuos que buscan expandir su conocimiento y habilidades en áreas específicas. Estos usuarios pueden acceder a cursos personalizados que se ajustan a su nivel de experiencia y ritmo de aprendizaje.

- Educadores:
Profesores y formadores que buscan complementar su material didáctico con recursos interactivos y actualizados. La plataforma permite a los educadores enriquecer su enseñanza con contenido diverso y herramientas de valuación avanzadas.

- Administradores:
Responsables de gestionar y supervisar la plataforma, asegurando que el contenido sea relevante, actualizado y de alta calidad. Los administradores también juegan un papel crucial en la moderación de la comunidad de usuarios, la implementación de mejoras basadas en la retroalimentación y el mantenimiento de la infraestructura técnica de Learnique.

## Listado de scripts para las vistas

### Pagina Principal
- index.php : Pantalla principal de la pagina web. 

### Comun
- topBar.php : Cabecera de la web

- box_curso.php : ################################

- curso.php : ################################

### Plantilla
- plantilla.php : 

### F1: Gestión de Roles: Estudiante, Profesor, Administrador
- login.php : Pantalla de login

- registro.php : Pantalla de registro

- logout.php : Pantalla de logout

### F2: Gestión de Inscripciones y Matriculaciones
- inscripcion.php : Pantalla de inscripción a un curso (se agrega el curso al carrito)

- carrito.php : Pantalla de carrito de compras 

### F3: Gestión de Búsqueda con Filtros
- cursos.php : Pantalla de listado de cursos. A partir de ahí, podemos seleccionar el curso para acceder a la información que deseamos.

  - trading.php : vista de el curso de trading 
  
  - blockchain.php : vista de el curso de blockchain
  
  - cripto.php : vista de el curso de criptomonedas 
  
  - marketing.php : vista de el curso de marketing
  
    
(estos cuatros cursos son ejemplos para entender lo que queremos hacer despues con la base de datos.)

- curso.php : vista para un curso en particular, va a reemplazar los 4 previos.

- buscar_cursos.php : ################################

### F4: Panel de Administración
- ajustes.php : ################################

- actualizar_cursos.php : ################################

- anadirCurso.php : Pantalla de añadir curso
- editarCurso.php : Pantalla de editar curso
- eliminarCurso.php : Pantalla de eliminar curso

### F5: Gestión de Comunicación: Estudiantes y Profesores
- chat.php : Pantalla de chat


## Listado de scripts adicionales


## Estructura de la base de datos


## Prototipo funcional del proyecto

## VPS

## Actividades de los integrantes










